# Generated by Django 2.1.1 on 2018-10-05 12:22

from django.db import migrations, models
import my_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20181005_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to=my_app.models.user_directory_path),
        ),
    ]
